# Generated by Django 4.0.5 on 2022-06-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dinosaur_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='country',
            field=models.ManyToManyField(related_name='dinosaurs', to='dinosaur_app.country'),
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='diet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dinosaur_app.diet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='mesozoic',
            field=models.ManyToManyField(related_name='dinosaurs', to='dinosaur_app.mesozoic'),
        ),
    ]
