# Generated by Django 4.0.5 on 2022-06-13 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur_app', '0002_dinosaur_category_dinosaur_country_dinosaur_diet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesozoic',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mesozoic',
            name='start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='dinosaur_app.category'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='dinosaur_app.diet'),
        ),
    ]
