# Generated by Django 4.0.5 on 2022-06-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur_app', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='desire',
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='dinosaur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='dinosaur_app.dinosaur'),
        ),
    ]
