# Generated by Django 4.0.5 on 2022-06-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur_app', '0005_diet_desire_alter_image_dinosaur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='desire',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
