# Generated by Django 4.0.5 on 2022-06-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur_app', '0006_alter_diet_desire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='desire',
            field=models.TextField(default='Nothing', max_length=500, null=True),
        ),
    ]
