# Generated by Django 4.0.5 on 2022-06-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur_app', '0007_alter_diet_desire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='desire',
        ),
    ]
