# Generated by Django 4.0.5 on 2022-06-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur_app', '0008_remove_diet_desire'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='desire',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
